"""API request/response schemas."""

from .images import (
    DeleteImageResponse,
    GenerateImageRequest,
    GenerateTaskResponse,
    GetImagesResponse,
    SelectImageRequest,
    SelectImageResponse,
)
from .slides import (
    CostResponse,
    CreateSlideRequest,
    DeleteProjectResponse,
    DeleteSlideResponse,
    GetEngineResponse,
    ProjectListResponse,
    ProjectResponse,
    ProjectSummaryResponse,
    ReorderSlidesRequest,
    ReorderSlidesResponse,
    SlideImageResponse,
    SlideResponse,
    StyleResponse,
    UpdateEngineRequest,
    UpdateEngineResponse,
    UpdateSlideRequest,
    UpdateTitleRequest,
    UpdateTitleResponse,
)
from .style import (
    GenerateStyleFromTemplateRequest,
    GenerateStyleFromTemplateResponse,
    GenerateStyleRequest,
    GenerateStyleResponse,
    GetStyleResponse,
    SaveStyleRequest,
    SaveStyleResponse,
    StyleCandidateResponse,
    StyleTemplateResponse,
    StyleTemplatesResponse,
)

__all__ = [
    # Slides
    "CostResponse",
    "CreateSlideRequest",
    "DeleteProjectResponse",
    "DeleteSlideResponse",
    "GetEngineResponse",
    "ProjectListResponse",
    "ProjectResponse",
    "ProjectSummaryResponse",
    "ReorderSlidesRequest",
    "ReorderSlidesResponse",
    "SlideImageResponse",
    "SlideResponse",
    "StyleResponse",
    "UpdateEngineRequest",
    "UpdateEngineResponse",
    "UpdateSlideRequest",
    "UpdateTitleRequest",
    "UpdateTitleResponse",
    # Style
    "GenerateStyleFromTemplateRequest",
    "GenerateStyleFromTemplateResponse",
    "GenerateStyleRequest",
    "GenerateStyleResponse",
    "GetStyleResponse",
    "SaveStyleRequest",
    "SaveStyleResponse",
    "StyleCandidateResponse",
    "StyleTemplateResponse",
    "StyleTemplatesResponse",
    # Images
    "DeleteImageResponse",
    "GenerateImageRequest",
    "GenerateTaskResponse",
    "GetImagesResponse",
    "SelectImageRequest",
    "SelectImageResponse",
]
